### ISSUE TITLE
New classes in java.util.concurrent.atomic

### ISSUE THREAD

**Issue by LangVE** [LangVE/java-8-api#16]
## 완료 목표
* LongAdder, LongAccumulator 클래스의 사용법에 대해서 학습한다.

## 완료 기한
2017.04.26 (수)

**Comment by LangVE** [comment]
### 참고
https://liviutudor.com/2014/06/26/java-8-accumulators-and-adders

**Comment by leesangdeok** [comment]
참고
http://winterbe.com/posts/2015/04/30/java8-concurrency-tutorial-synchronized-locks-examples/
